### ISSUE TITLE
Smartphone Experimentation App Social Auth

### ISSUE THREAD

**Issue by SimKennedy** [OrganicityEu/organicityeu.github.io#1]
Hi,

I am using my Google social Auth for my Organicity Experimenters account on the website and you say that you can login using the same account on the app to test your experiments. I have download the app and the login screen asks for a username and password but does not seem to show a social auth option and I can't see where to retrieve a password anywhere online?

Sim

**Comment by amaxilat** [comment]
Hi @SimKennedy, the social login buttons are on the right hand side of the login form and you should use them to login.
I have also found an issue causing the social login button to not work when pressed and updated in the play store. You should shortly receive an update to the app with the new version.

Please keep in mind that the update may take a few hours to reach the public.

When you do let me know if that works for you.

**Comment by SimKennedy** [comment]
Hi @amaxilat, thanks for the reply.

I just noticed that I could get to my account settings on the desktop through a "Profile" button located at the top right of the http://staging.observatory.organicity.eu/ website when logged in. (I note that this button is not available on the experimenters page: https://experimenters.organicity.eu.) In these settings I could set a password for my account and have managed to login to the app this way.

I have since tried to test the Google auth but each time I click on `Disconnect Organicity account` and then click on  `Login` again it automatically uses the saved password, and I can not see a way to "forget" the saved login anywhere? I managed to clear the saved login by clearing the stored data in the android app management.

I see the problem with the social auth in the app is it is not rendering correctly and the buttons are off the screen. Unfortunately I can not pan the website across to the buttons to use them. I have attached a screenshot of the furthest across I can pan the login page.

For now I can login with the password though.

Thanks

Sim
![organicity_login_problem](https://cloud.githubusercontent.com/assets/9877685/19115180/e2119a28-8b08-11e6-9df7-55cb56af613f.png)

**Comment by amaxilat** [comment]
Yes the issue for not being able to log out is related to the browser's session in the Android WebView (something we cannot tamper with).
To change this you can : 
- disconnect your account and wait for a few minutes or
- clear the application data from the Android Application menu

The update is not yet public in the Play Store, so you will have to wait or log in via the password your created.

**Comment by fbuether** [comment]
@amaxilat There is a log-out functionality you could use in the same manner as the login-screen. I'll research that and let you know as soon as I know more.

Wrt. the (pretty unusable) login-screen: I am working on this and will post here when this is fixed.

**Comment by fbuether** [comment]
I fixed the login screen, so even from mobile it should now be viewable and usable; @amaxilat could you please check from the app, and close this issue if it is okay?

I also posted a bit about a log-out procedure, in case you want to integrate a log-out button in the app.

**Comment by amaxilat** [comment]
I think its no longer an issue so I will close it for now
