### ISSUE TITLE
Issue with pushing asset as participant

### ISSUE THREAD

**Issue by AleksaNissatech** [OrganicityEu/organicityeu.github.io#6]
Hi! I'm having a problem with pushing an asset as a participant. I'm following these instructions https://github.com/OrganicityEu/organicityeu.github.io/blob/master/doc/HowToPushAnAssetToTheExperimenterSite.md and it works for pushing an asset as experimenter. However, the same request format doesn't work for a participant. I added the participant to my experiment via experimenter portal and he accepted to be a part of experiment before the push was tried. I get 502 error code after about 20 sec. Is there something about Asset ID field format, request headers or something third specific for participants that I'm missing? 
![asset-push-error](https://cloud.githubusercontent.com/assets/25434632/22427321/ff823cb0-e702-11e6-9001-0b4b9088d03a.png)

**Comment by AleksaNissatech** [comment]
I'm not sure if this is the right place for this type of request but here it goes:
 Can someone please enable Client Credential Grant for our experiment? Our experiment id is: 585bf94a3be86fb040943809
Thanks

**Comment by boldt** [comment]
Can you contact me on the experimenters slack? So we can chat about the issue?
